from datetime import datetime

class ExportManager:
    """
    Gère la transformation des données brutes en documents lisibles (Markdown/Text).
    """
    
    def generate_markdown(self, root_data):
        """
        Crée une fiche technique formatée pour une racine donnée.
        Retourne : (filename, content_string)
        """
        timestamp = datetime.now().strftime("%Y-%m-%d")
        root_code = root_data.get('root', 'UNKNOWN')
        filename = f"VERITAS_ANALYSIS_{root_code}_{timestamp}.md"
        
        # Construction du rapport
        content = f"""# 🏛 VERITAS KERNEL REPORT
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Target:** {root_code} ({root_data.get('arabic', '')})

---

## 1. SYSTEM IDENTITY
* **Root ID:** `{root_code}`
* **Native Script:** `{root_data.get('arabic', '')}`

## 2. LOGIC FUNCTION
> **{root_data.get('logic_function', 'N/A')}**

## 3. TECHNICAL DESCRIPTION
{root_data.get('description', 'No description available.')}

---
*Generated by Veritas Kernel v10.4 - Digital Humanities Engine*
"""
        return filename, content

